post_install() {

mv -fv /usr/src/linux/5.15.4/src/linux-5.15.4 /usr/src/linux-5.15.4
ln -sfv /usr/src/linux-5.15.4 /lib/modules/5.15.4/source 
rm -rf /usr/src/linux/5.15.4/src
rm -rf /usr/src/linux/5.15.4/pkg
chown -R root /usr/src/linux-5.15.4
rm -rf /usr/src/linux/5.15.4/src
ln -sfv /usr/src/linux-5.15.4 /lib/modules/5.15.4/build
rm -v /usr/src/linux/5.15.4/linux-5.15.4.tar.xz
mv -v /usr/src/linux/5.15.4/linux-5.15.4-1-x86_64.pkg.tar.gz /var/cache/pacman/pkg

}
